theme = "molokai"

[editor]
scrolloff = 999
mouse = false
line-number = "relative"
cursorline = true
rulers = [100]
auto-format = false

[keys.normal]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]

x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]

w = ["move_next_word_start", "move_char_right", "collapse_selection"]
W = ["move_next_long_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
E = ["move_next_long_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
B = ["move_prev_long_word_start", "collapse_selection"]

C-r = ["redo"]
u = ["undo", "collapse_selection"]

esc = ["collapse_selection", "keep_primary_selection"]

j = "move_line_down"
k = "move_line_up"

[keys.normal.c]
w = ["delete_word_forward", "insert_mode"]
c = ["goto_line_start", "insert_mode", "kill_to_line_end"]
l = ["delete_char_forward", "insert_mode"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
l = ["delete_char_forward"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
c = "change_selection"

i = "select_textobject_inner"
a = "select_textobject_around"

k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
