theme = "molokai"

[editor]
scrolloff = 999
mouse = false
line-number = "relative"
cursorline = true
auto-format = true
completion-timeout = 5

[editor.statusline]
left = ["mode", "spacer", "version-control"]
right = ["diagnostics", "position", "total-line-numbers", "spinner", "spacer"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]

[editor.file-picker]
git-ignore = false

[editor.lsp]
display-messages = true
snippets = false

[keys.normal]
X = ["extend_line_above"]
C = ["collapse_selection", "extend_to_line_end", "delete_selection", "insert_mode"]
esc = ["keep_primary_selection", "collapse_selection"]

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
e = "changed_file_picker"
