[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "scss"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "sql"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "sed", args = ["s/[ \t]*$//"] }
auto-format = true

[[language]]
name = "latex"
language-servers = ["textlab", "typos"]

[language-server.typos]
command = "typos-lsp"
